### ISSUE TITLE
ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by luminous8** [harvard-lil/waczerciser#1]
Hey,

I'm trying to test the package and getting this error
`Error: ENAMETOOLONG: name too long, open 'stripe/archive/data/https:/q.stripe.com/?domain=stripe.com&page=%2Fen-fr%2Fcontact%2Fsales&referrer=https%3A%2F%2Fstripe.com%2Fen-fr%2Fenterprise&cid=fa0e70f1-4437-4c8a-8d0b-0ab6c98ef8ee&lsid=fa0e70f1-4437-4c8a-8d0b-0ab6c98ef8ee&viewport_height=811&viewport_width=1440&analytics_ua=analytics.js-CURRENT_VERSION&ua_browser_name=Brave&ua_browser_version=131.0.0.0&ua_os_name=Mac%20OS&ua_os_version=10.15.7&ua_device_model=Macintosh&ua_device_vendor=Apple&ua_engine_name=Blink&ua_engine_version=131.0.0.0&category=Custom%20interactive%20components&label=Cookie%20notification%20(Reject%20all)%3A%20Banner%20displayed&value=undefined&from_mkt_srv=true&document_height=1580&scroll_y=0&stripe_locale=en-FR&unglobalized_path=%2Fcontact%2Fsales&logged_in=true&has_logged_in_last_six_months=true&action_name=viewed&viewed_name=contact_sales_page&event=viewed.action&event_count=2&page_view_id=da64c847-b957-43f7-b0e1-b6377ae6a912&event_id=da64c847-b957-43f7-b0e1-b6377ae6a912_2&privacy_consent_loaded=true&privacy_consent_advertising=false&privacy_consent_functional=false'`

I've tried with other wacz files and getting this as well with google analytics links for example

Any way to fix this?

Thanks

**Comment by bensteinberg** [comment]
I think we need to change the extract command to name the output directory with something other than a very long filename; I'll see if I can come up with a fix.

**Comment by bensteinberg** [comment]
(If I'm right about what's happening, you could rename the WACZ file with a short filename and try to extract again.)

**Comment by luminous8** [comment]
Thanks! I think the issue is not about the wacz filename length but the length of the urls store in the wacz file

in fact i've renamed the wacz into "s.wacz" and still got the issue

**Comment by bensteinberg** [comment]
Thanks! I'll take another look.

**Comment by bensteinberg** [comment]
@luminous8 I have a fix in review, but in the meantime you could try it out from my fork:

    npx github:bensteinberg/waczerciser#limit-filename-length extract s.wacz

**Comment by luminous8** [comment]
Thanks @bensteinberg 🙏 

I've encounter a new error now `Error: ENOTDIR: not a directory, mkdir 'stripe/archive/data/https:/stripe.com/en-fr/contact'`

**Comment by bensteinberg** [comment]
That's strange. Is `contact` already there, and a file instead of a directory?

You might try running the extract command with the `--delete-existing` option.

**Comment by luminous8** [comment]
/en-fr is not a folder but a file 🤔 

<img width="248" alt="Capture d’écran 2024-12-06 à 18 46 32" src="https://github.com/user-attachments/assets/408dfc7c-b0b5-4bc1-a0c5-7df4f6dc39ff">

Hope that helps

**Comment by bensteinberg** [comment]
OK, I'm going to guess that the WARC file contains an exchange like `stripe.com/en-fr` and another one like `stripe.com/en-fr/contact` -- so when the extractor gets to the second one and wants to make a directory, it can't because it's already made the file `contact`. I think we probably need to do something to watch for and handle collisions like this. I might make another issue.

Depending on how you made or obtained the capture in question, would you be comfortable sharing it? Either here, or you could send it to me securely/out-of-band if you'd rather it not be public.

**Comment by bensteinberg** [comment]
Fixed in #2 -- I've opened #3 for the `ENOTDIR` error.
